# Default endpoint URLs for the ORCID OAuth API

production:
  site: http://api.orcid.org
  authorize_url: http://orcid.org/oauth/authorize
  token_url: http://api.orcid.org/oauth/token
  client_id: 
  client_secret: 

development:
  site: http://0.0.0.0:3000
  authorize_url: https://orcid.org/oauth/authorize
  token_url: https://pub.orcid.org/oauth/token
  client_id: <%= ENV["ORCID_KEY"] %>
  client_secret: <%= ENV["ORCID_SECRET"] %>

